AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Selenium webdriver tests.

service: SeleniumTest

provider:
  name: aws
  runtime: nodejs8.10
  stage: WDTest

functions:
  Selenium:
    handler: index.executeTest
    events:
      - http:
          path: runScript
          method: get

  Hello:
    handler: index.sample